# Generated by Django 3.2.21 on 2023-09-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_support'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accociate',
            old_name='parient',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='accociate',
            name='address',
            field=models.TextField(default='Enter Your Address...'),
        ),
        migrations.AddField(
            model_name='accociate',
            name='bank_ifsc',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='accociate',
            name='bank_name',
            field=models.CharField(default='Enter your bank Name..', max_length=150),
        ),
        migrations.AddField(
            model_name='accociate',
            name='branch_name',
            field=models.CharField(default='Branch Name..', max_length=200),
        ),
        migrations.AddField(
            model_name='accociate',
            name='nominee',
            field=models.CharField(default='Nominee Name', max_length=150),
        ),
        migrations.AlterField(
            model_name='accociate',
            name='level',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=150, null=True),
        ),
    ]
