# Generated by Django 3.2.21 on 2023-10-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_auto_20231005_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payemt',
            new_name='Paymemt',
        ),
    ]
