# Generated by Django 3.2.21 on 2023-10-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_rename_payemt_paymemt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paymemt',
            new_name='Payment',
        ),
    ]
