# Generated by Django 3.2.21 on 2023-10-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_rename_paymemt_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Done', 'Done'), ('Cancel', 'Cancel')], default='Pending', max_length=150),
        ),
    ]
