# Generated by Django 3.2.21 on 2023-11-01 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_auto_20231031_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.CharField(choices=[('ambassdor', 'ambassdor'), ('royal ruby', 'royal ruby'), ('ruby', 'ruby'), ('royal platinum', 'royal platinum'), ('platinum', 'platinum'), ('royal diamond', 'royal diamond'), ('diamond', 'diamond'), ('royal gold', 'royal gold'), ('gold', 'gold'), ('silver', 'silver'), ('bronze', 'bronze'), ('star', 'star')], max_length=250)),
                ('achiving_date', models.DateField(auto_now=True)),
                ('accociate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.accociate')),
            ],
        ),
    ]
