# Generated by Django 4.2.2 on 2023-10-30 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('gstin', models.CharField(max_length=250)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kit', models.PositiveIntegerField()),
                ('MRP', models.PositiveIntegerField()),
                ('DP', models.PositiveIntegerField()),
                ('BV', models.PositiveIntegerField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franchise.franchise')),
            ],
        ),
        migrations.CreateModel(
            name='activationHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activation_time', models.DateField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franchise.franchise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.accociate')),
            ],
        ),
    ]
