# Generated by Django 3.2.21 on 2023-10-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='available_kits',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
