# Generated by Django 3.2.21 on 2023-12-20 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_reward'),
        ('franchise', '0002_franchise_available_kits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('DP', models.PositiveIntegerField()),
                ('BV', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RepurchaseSellHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franchise.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franchise.franchise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.accociate')),
            ],
        ),
        migrations.CreateModel(
            name='RepurchaseSell',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franchise.product')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franchise.sell')),
            ],
        ),
        migrations.CreateModel(
            name='RepurchaseProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franchise.franchise')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franchise.product')),
            ],
        ),
    ]
