# Generated by Django 3.2.21 on 2024-01-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0003_product_repurchaseproduct_repurchasesell_repurchasesellhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='available_kits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
