# Generated by Django 3.2.21 on 2024-01-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0004_alter_franchise_available_kits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='available_kits',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
